### ISSUE TITLE
Meaning of relations with implicit extractions like "has:impl_poss-clause" or "is:impl_np-person"

### ISSUE THREAD

**Issue by Frankie123421** [samuelbroscheit/open_knowledge_graph_embeddings#2]
Hello, I have some questions about the relation meaning. There are some relation names that contain ":", for example, "has:impl_poss-clause" and "is:impl_np-person", I am confused about what they mean and what their actual names are, thank you.

**Comment by samuelbroscheit** [comment]
Hi! Thank you for your interest in this study and the dataset! 

This is additional information about how a triple was extracted. For example, "has:impl_poss-clause" was extracted from a sentence which did not explicitly say "New York has a mayor ...", but from the **impl**icit **poss**esive relation in "New York's mayor ...". OLPBENCH is based on OPIEC (https://openreview.net/forum?id=HJxeGb5pTm) which was created with the system MINIE (see Implicit extractions in https://aclanthology.org/D17-1278.pdf), which uses the patterns described in FINET (https://aclanthology.org/D15-1103.pdf). Check out the last two papers to learn more about the implicit extractions that can occur in this dataset. Some of those patterns can be noisy or might require special treatment. This is why I left this information in the data. For instance, for the evaluation data I chose the heuristic to sample only from relations with three or more words. This automatically excluded some of the more noisy implicit extractions that I deemed to noisy for evaluation. For training they will give you some signal, but some types of implicit relations are more noisy than others. If you want to use those triples for a model that cannot handle this additional information then a simple approach is to just ignore everything after the colon.

That was a good question and maybe a bit windy to track down if you are new to OIE. I should add this information somewhere in this README. Please leave this issue open. I'll close it when I have added this info in the main README.

**Comment by Frankie123421** [comment]
Thanks for your kind reply, it is of great help to me. I will leave this issue open.
